/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proto1c;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michael
 */
public class gui_Event extends javax.swing.JFrame {
    private final manager_userClient userClientParent;

    /**
     * Creates new form gui_Event
     * @param userClient
     */
    public gui_Event(manager_userClient userClient) {
        userClientParent = userClient;
        initComponents();
    }
    
       public void loadList(ArrayList <type_TableRow> allEvents) {
        eventList.setRowHeight(40);
        DefaultTableModel model = (DefaultTableModel) eventList.getModel();
            
        for (int i = (eventList.getRowCount() -1); i >= 0; i--) {
            model.removeRow(i);
        }
            
        for (int i = 0; i < allEvents.size(); i++) {
            model.addRow(new Object[]{allEvents.get(i).getTblName(), allEvents.get(i).getTblType(), allEvents.get(i).getTblTime() + " " + allEvents.get(i).getTblDate()}); 
        }
    }
    gui_Event() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        Edit1 = new javax.swing.JButton();
        Del1 = new javax.swing.JButton();
        Edit2 = new javax.swing.JButton();
        Del2 = new javax.swing.JButton();
        Del3 = new javax.swing.JButton();
        Edit4 = new javax.swing.JButton();
        Edit5 = new javax.swing.JButton();
        Del4 = new javax.swing.JButton();
        Del5 = new javax.swing.JButton();
        Edit3 = new javax.swing.JButton();
        evt_back = new javax.swing.JButton();
        evt_back1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Events");

        Edit1.setText("Edit");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });

        Del1.setText("Delete");
        Del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del1ActionPerformed(evt);
            }
        });

        Edit2.setText("Edit");
        Edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit2ActionPerformed(evt);
            }
        });

        Del2.setText("Delete");
        Del2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del2ActionPerformed(evt);
            }
        });

        Del3.setText("Delete");
        Del3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del3ActionPerformed(evt);
            }
        });

        Edit4.setText("Edit");
        Edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit4ActionPerformed(evt);
            }
        });

        Edit5.setText("Edit");
        Edit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit5ActionPerformed(evt);
            }
        });

        Del4.setText("Delete");
        Del4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del4ActionPerformed(evt);
            }
        });

        Del5.setText("Delete");
        Del5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del5ActionPerformed(evt);
            }
        });

        Edit3.setText("Edit");
        Edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit3ActionPerformed(evt);
            }
        });

        evt_back.setText("Back");
        evt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evt_backActionPerformed(evt);
            }
        });

        evt_back1.setText("Create");
        evt_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evt_back1ActionPerformed(evt);
            }
        });

        eventList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eventList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event:", "Event Type:", "Event Date & Time:", "Edit?:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventListMouseClicked(evt);
            }
        });
        eventList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                eventListPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(eventList);
        if (eventList.getColumnModel().getColumnCount() > 0) {
            eventList.getColumnModel().getColumn(0).setResizable(false);
            eventList.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(evt_back1)
                        .addGap(18, 18, 18)
                        .addComponent(evt_back)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Edit1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Del1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Edit2)
                                    .addComponent(Edit4)
                                    .addComponent(Edit5)
                                    .addComponent(Edit3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Del3)
                                    .addComponent(Del2)
                                    .addComponent(Del4)
                                    .addComponent(Del5))))
                        .addContainerGap(216, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(evt_back)
                            .addComponent(evt_back1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit1)
                            .addComponent(Del1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit2)
                            .addComponent(Del2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Del3)
                            .addComponent(Edit3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit4)
                            .addComponent(Del4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit5)
                            .addComponent(Del5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
        gui_Eventedit a = new gui_Eventedit();
        a.setVisible(true);
    }//GEN-LAST:event_Edit1ActionPerformed

    private void Edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit2ActionPerformed
        gui_Eventedit b = new gui_Eventedit();
        b.setVisible(true);
    }//GEN-LAST:event_Edit2ActionPerformed
   
    private void Del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?\n" + "This action cannot be undone.", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            //label1.setVisible(false);
            Edit1.setVisible(false);
            Del1.setVisible(false);
        }
    }//GEN-LAST:event_Del1ActionPerformed

    private void Del2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?\n" + "This action cannot be undone.", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
          //  label2.setVisible(false);
            Edit2.setVisible(false);
            Del2.setVisible(false);
        }
    }//GEN-LAST:event_Del2ActionPerformed

    private void Del3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del3ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?\n" + "This action cannot be undone.", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
         //   label3.setVisible(false);
            Edit3.setVisible(false);
            Del3.setVisible(false);
        };
    }//GEN-LAST:event_Del3ActionPerformed

    private void Del4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del4ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?\n" + "This action cannot be undone.", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        //    label4.setVisible(false);
            Edit4.setVisible(false);
            Del4.setVisible(false);
        }
    }//GEN-LAST:event_Del4ActionPerformed

    private void Del5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del5ActionPerformed
       int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?\n" + "This action cannot be undone.", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        //    label5.setVisible(false);
            Edit5.setVisible(false);
            Del5.setVisible(false);
        }
    }//GEN-LAST:event_Del5ActionPerformed

    private void Edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit3ActionPerformed
        gui_Eventedit c = new gui_Eventedit();
        c.setVisible(true);
    }//GEN-LAST:event_Edit3ActionPerformed

    private void Edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit4ActionPerformed
        gui_Eventedit d = new gui_Eventedit();
        d.setVisible(true);
    }//GEN-LAST:event_Edit4ActionPerformed

    private void Edit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit5ActionPerformed
        gui_Eventedit e = new gui_Eventedit();
        e.setVisible(true);
    }//GEN-LAST:event_Edit5ActionPerformed

    private void evt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evt_backActionPerformed
        // Once clicked, it will take the user back to the main screen to access other features
        userClientParent.back();
    }//GEN-LAST:event_evt_backActionPerformed

    private void evt_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evt_back1ActionPerformed
        // TODO add your handling code here:
        gui_EventNew n= new gui_EventNew();
        n.setVisible(true);
    }//GEN-LAST:event_evt_back1ActionPerformed

    private void eventListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventListMouseClicked
        String value = eventList.getModel().getValueAt(eventList.getSelectedRow(), eventList.getSelectedColumn()).toString();
        int row = eventList.getSelectedRow();

        double cost = Double.valueOf(eventList.getModel().getValueAt(row, 2).toString().replace("£", ""));

        if (value.equals("true")) {
            userClientParent.spendingListCheck(new type_TableRow(eventList.getModel().getValueAt(row, 1).toString(), cost, Integer.valueOf(eventList.getModel().getValueAt(row, 0).toString())));
        }
    }//GEN-LAST:event_eventListMouseClicked

    private void eventListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_eventListPropertyChange

    }//GEN-LAST:event_eventListPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del1;
    private javax.swing.JButton Del2;
    private javax.swing.JButton Del3;
    private javax.swing.JButton Del4;
    private javax.swing.JButton Del5;
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Edit2;
    private javax.swing.JButton Edit3;
    private javax.swing.JButton Edit4;
    private javax.swing.JButton Edit5;
    private javax.swing.JTable eventList;
    private javax.swing.JButton evt_back;
    private javax.swing.JButton evt_back1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
