package proto1c;
import java.text.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 **Class that creates the GUI for the Budget.
 **@author UP875166
 */
public class gui_Budget extends javax.swing.JFrame {
private final manager_userClient userClient;
    /**
     * Creates new form gui_Budget
     */
    public gui_Budget(manager_userClient userClientParent) {
        initComponents();
        userClient = userClientParent;
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        budgetPanel = new javax.swing.JPanel();
        budgetText = new javax.swing.JLabel();
        budget = new javax.swing.JTextField();
        updateBudget = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userBudget = new javax.swing.JTextArea();
        clearBudget1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        budgetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Budget", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N
        budgetPanel.setToolTipText("Date");

        budgetText.setText("Monthly Budget (£) :");

        budget.setText("0.00");
        budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout budgetPanelLayout = new javax.swing.GroupLayout(budgetPanel);
        budgetPanel.setLayout(budgetPanelLayout);
        budgetPanelLayout.setHorizontalGroup(
            budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(budgetText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        budgetPanelLayout.setVerticalGroup(
            budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetText)
                    .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        updateBudget.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateBudget.setText("Update Budget");
        updateBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBudgetActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        userBudget.setColumns(20);
        userBudget.setRows(5);
        userBudget.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(userBudget);

        clearBudget1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        clearBudget1.setText("Clear");
        clearBudget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBudget1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBudget)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBudget1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(updateBudget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBudget1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userClient.back();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetActionPerformed
    float f = Float.parseFloat(budget.getText());
    }//GEN-LAST:event_budgetActionPerformed

    private void updateBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBudgetActionPerformed
        NumberFormat formatter = new DecimalFormat("#0.00");   
        userBudget.setText("");
        float f = Float.parseFloat(budget.getText());
        double weeklyBudget = f/4;

        f = Float.parseFloat(budget.getText());
        float yearlyBudget = (int) (f * 12);
        float dailyBudget = yearlyBudget/365;

        userBudget.setText(userBudget.getText() + "Monthly Budget:" + formatter.format(f));
        userBudget.setText(userBudget.getText() + "\nWeekly Budget: " + formatter.format(weeklyBudget));
        userBudget.setText(userBudget.getText() + "\nDaily Budget: " + formatter.format(dailyBudget));
    }//GEN-LAST:event_updateBudgetActionPerformed

    private void clearBudget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBudget1ActionPerformed
        budget.setText("0.00");
        userBudget.setText("");
    }//GEN-LAST:event_clearBudget1ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budget;
    private javax.swing.JPanel budgetPanel;
    private javax.swing.JLabel budgetText;
    private javax.swing.JButton clearBudget1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBudget;
    private javax.swing.JTextArea userBudget;
    // End of variables declaration//GEN-END:variables

    private float f;
    private int weeklyBudget;
    private int dailyBudget;
}
